config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Site root
  root 'static_pages#home'

  # User routes
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :keys
  resources :remotes
  resources :devices
  resources :device_types
  resources :device_models
  resources :device_brands
  resources :locations
end

app/models/remote.rb
class Remote < ApplicationRecord
  # Associations
  has_many :keys
  has_and_belongs_to_many :device_models
  belongs_to :brand,
               class_name: 'DeviceBrand',
               foreign_key: 'brand_id'
  belongs_to :submitter,
               class_name: 'User',
               foreign_key: 'submitter_id'

  # Validations
  ## Name validations
  VALID_NAME_REGEX = /\A[\w -]+\z/
  validates :name,
              format: { with: VALID_NAME_REGEX },
              length: { in: 2..50 },
              presence: true
  ## Submitter validations
  validates :submitter,
              presence: true
  ## Brand validations
  validates :brand,
              presence: true
  ## Model validations
  VALID_MODEL_REGEX = /\A[\w -]+\z/
  validates :model,
              format: { with: VALID_MODEL_REGEX },
              length: { in: 2..50 },
              presence: true,
              uniqueness: { scope: :brand,
                            message: "Remote already exists." }
  ## Supported devices validations
  ### TODO Ideally should create HABTM for device_models relation rather than string
  VALID_DEVICE_REGEX = /\A[a-zA-Z ]+\z/
  validates :supported_devices,
              allow_nil: true,
              format: { with: VALID_DEVICE_REGEX },
              length: { in: 2..50 }
  ## Eps validations 
  validates :eps,
              allow_nil: true,
              inclusion: { in: 0..100 }
  ## Aeps validations 
  validates :aeps,
              allow_nil: true,
              inclusion: { in: 0..100 }
  ## Duty cycle validations
  validates :duty_cycle,
              allow_nil: true,
              inclusion: { in: 0..100 }

  # Custom Validations
  validate :flags_are_formatted_properly

  # Custom Methods

  # Private Methods
  private

    # Validation methods
    def flags_are_formatted_properly
      # Ensures flags string is properly formatted with no repeats
      allowed_flags = %w[RC5
                         RC6
                         RCMM
                         SHIFT_ENC
                         SPACE_ENC
                         REVERSE
                         NO_HEAD_REP
                         NO_FOOT_REP
                         CONST_LENGTH
                         RAW_CODES
                         REPEAT_HEADER
      ]
      unless self.flags.blank?
        # Validate flags are allowed
        flag_array = self.flags.split('|')
        ## Make sure no repeated flags
        flag_array.each do |flag|
          flag.squish!
        end
        flag_array.uniq! # remove any duplicate flags
        # Validate all flags are allowed, must be case-sensitive
        flag_array.each do |flag|
          unless flag.in? allowed_flags
            errors.add(:flags, "has improper flag: #{flag}")
          end
        end
        # Clean and rebuild flag string
        self.flags = flag_array.join(' | ')
      end
    end
    
    # Other private methods

end

app/controllers/remotes_controller.rb
class RemotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_remote, only: [:show, :edit, :update, :destroy]

  # GET /remotes
  # GET /remotes.json
  def index
    @remotes = Remote.all
  end

  # GET /remotes/1
  # GET /remotes/1.json
  def show
  end

  # GET /remotes/new
  def new
    @remote = Remote.new
    @device_brands = DeviceBrand.all
    @device_models = DeviceModel.all
  end

  # GET /remotes/1/edit
  def edit
    @device_brands = DeviceBrand.all
    @device_models = DeviceModel.all
  end

  # POST /remotes
  # POST /remotes.json
  def create
    @device_brands = DeviceBrand.all
    @device_models = DeviceModel.all
    @remote = current_user.submitted_remotes.new(remote_params)

    respond_to do |format|
      if @remote.save
        format.html { redirect_to @remote, notice: 'Remote was successfully created.' }
        format.json { render :show, status: :created, location: @remote }
      else
        format.html { render :new }
        format.json { render json: @remote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /remotes/1
  # PATCH/PUT /remotes/1.json
  def update
    respond_to do |format|
      if @remote.update(remote_params)
        format.html { redirect_to @remote, notice: 'Remote was successfully updated.' }
        format.json { render :show, status: :ok, location: @remote }
      else
        format.html { render :edit }
        format.json { render json: @remote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /remotes/1
  # DELETE /remotes/1.json
  def destroy
    @remote.destroy
    respond_to do |format|
      format.html { redirect_to remotes_url, notice: 'Remote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_remote
      @remote = Remote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def remote_params
      params.require(:remote).permit(:name, :brand_id, 
                                     :model, :supported_devices, :bits, 
                                     :flags, :include, :manual_sort, 
                                     :suppress_repeat, :driver, :eps, :aeps, 
                                     :header, :zero, :one, :two, :three, 
                                     :ptrail, :plead, :foot, :repeat, 
                                     :pre_data_bits, :pre_data, 
                                     :post_data_bits, :post_data, 
                                     :pre, :post, 
                                     :gap, :repeat_gap, :min_repeat, 
                                     :toggle_bit, :toggle_bit_mask, 
                                     :repeat_mask, :frequency, :duty_cycle,
                                     :device_model_ids => [])
    end
end

app/helpers/remotes_helper.rb
module RemotesHelper
end

app/views/remotes/_form.html.erb
<%= form_with(model: remote, local: true) do |f| %>
  <% if remote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(remote.errors.count, "error") %> prohibited this remote from being saved:</h2>

      <ul>
      <% remote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, id: :remote_name %>
  </div>

  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model, id: :model %>
  </div>

  <div class="field">
    <%= f.label :brand %>
    <%= f.select :brand_id, 
    @device_brands.collect { |b| [ b.name, b.id ] }, 
    { include_blank: false }, { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.label :device_model_ids, "Device Models Supported", class: 'col-sm-4 control-label' %>
    <div class="col-sm-8">
      <div class="container-fluid">
        <div class="row">
          <%= f.collection_check_boxes :device_model_ids,
            @device_models, :id, :name, {}, {} do |c|%>
            <div class="col-sm-6">
              <%= 
                c.label(class: 'checkbox') { 
                  c.check_box + " #{c.text} (#{c.object.brand.name})" 
                }
              %>
            </div>
          <% end %> 
        </div>
      </div>
    </div>
  </div>

  <div class="field">
    <%= f.label :supported_devices %>
    <%= f.text_field :supported_devices, id: :remote_supported_devices %>
  </div>

  <div class="field">
    <%= f.label :bits %>
    <%= f.number_field :bits, id: :remote_bits %>
  </div>

  <div class="field">
    <%= f.label :flags %>
    <%= f.text_field :flags, id: :remote_flags %>
  </div>

  <div class="field">
    <%= f.label :include %>
    <%= f.text_field :include, id: :remote_include %>
  </div>

  <div class="field">
    <%= f.label :manual_sort %>
    <%= f.check_box :manual_sort, id: :remote_manual_sort %>
  </div>

  <div class="field">
    <%= f.label :suppress_repeat %>
    <%= f.number_field :suppress_repeat, id: :remote_suppress_repeat %>
  </div>

  <div class="field">
    <%= f.label :driver %>
    <%= f.text_field :driver, id: :remote_driver %>
  </div>

  <div class="field">
    <%= f.label :eps %>
    <%= f.number_field :eps, id: :remote_eps %>
  </div>

  <div class="field">
    <%= f.label :aeps %>
    <%= f.number_field :aeps, id: :remote_aeps %>
  </div>

  <div class="field">
    <%= f.label :header %>
    <%= f.text_field :header, id: :remote_header %>
  </div>

  <div class="field">
    <%= f.label :zero %>
    <%= f.text_field :zero, id: :remote_zero %>
  </div>

  <div class="field">
    <%= f.label :one %>
    <%= f.text_field :one, id: :remote_one %>
  </div>

  <div class="field">
    <%= f.label :two %>
    <%= f.text_field :two, id: :remote_two %>
  </div>

  <div class="field">
    <%= f.label :three %>
    <%= f.text_field :three, id: :remote_three %>
  </div>

  <div class="field">
    <%= f.label :ptrail %>
    <%= f.number_field :ptrail, id: :remote_ptrail %>
  </div>

  <div class="field">
    <%= f.label :plead %>
    <%= f.number_field :plead, id: :remote_plead %>
  </div>

  <div class="field">
    <%= f.label :foot %>
    <%= f.text_field :foot, id: :remote_foot %>
  </div>

  <div class="field">
    <%= f.label :repeat %>
    <%= f.text_field :repeat, id: :remote_repeat %>
  </div>

  <div class="field">
    <%= f.label :pre_data_bits %>
    <%= f.number_field :pre_data_bits, id: :remote_pre_data_bits %>
  </div>

  <div class="field">
    <%= f.label :pre_data %>
    <%= f.text_field :pre_data, id: :remote_pre_data %>
  </div>

  <div class="field">
    <%= f.label :post_data_bits %>
    <%= f.number_field :post_data_bits, id: :remote_post_data_bits %>
  </div>

  <div class="field">
    <%= f.label :post_data %>
    <%= f.text_field :post_data, id: :remote_post_data %>
  </div>

  <div class="field">
    <%= f.label :pre %>
    <%= f.text_field :pre, id: :remote_pre %>
  </div>

  <div class="field">
    <%= f.label :post %>
    <%= f.text_field :post, id: :remote_post %>
  </div>

  <div class="field">
    <%= f.label :gap %>
    <%= f.number_field :gap, id: :remote_gap %>
  </div>

  <div class="field">
    <%= f.label :repeat_gap %>
    <%= f.number_field :repeat_gap, id: :remote_repeat_gap %>
  </div>

  <div class="field">
    <%= f.label :min_repeat %>
    <%= f.number_field :min_repeat, id: :remote_min_repeat %>
  </div>

  <div class="field">
    <%= f.label :toggle_bit %>
    <%= f.number_field :toggle_bit, id: :remote_toggle_bit %>
  </div>

  <div class="field">
    <%= f.label :toggle_bit_mask %>
    <%= f.text_field :toggle_bit_mask, id: :remote_toggle_bit_mask %>
  </div>

  <div class="field">
    <%= f.label :repeat_mask %>
    <%= f.text_field :repeat_mask, id: :remote_repeat_mask %>
  </div>

  <div class="field">
    <%= f.label :frequency %>
    <%= f.number_field :frequency, id: :remote_frequency %>
  </div>

  <div class="field">
    <%= f.label :duty_cycle %>
    <%= f.number_field :duty_cycle, id: :remote_duty_cycle %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/remotes/edit.html.erb
<h1>Editing Remote</h1>

<%= render 'form', remote: @remote %>

<%= link_to 'Show', @remote %> |
<%= link_to 'Back', remotes_path %>

app/views/remotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Remotes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Brand</th>
      <th>Model</th>
      <th>Supported devices</th>
      <th>Bits</th>
      <th>Flags</th>
      <th>Include</th>
      <th>Manual sort</th>
      <th>Suppress repeat</th>
      <th>Driver</th>
      <th>Eps</th>
      <th>Aeps</th>
      <th>Header</th>
      <th>Zero</th>
      <th>One</th>
      <th>Two</th>
      <th>Three</th>
      <th>Ptrail</th>
      <th>Plead</th>
      <th>Foot</th>
      <th>Repeat</th>
      <th>Pre data bits</th>
      <th>Pre data</th>
      <th>Post data bits</th>
      <th>Post data</th>
      <th>Pre</th>
      <th>Post</th>
      <th>Gap</th>
      <th>Repeat gap</th>
      <th>Min repeat</th>
      <th>Toggle bit</th>
      <th>Toggle bit mask</th>
      <th>Repeat mask</th>
      <th>Frequency</th>
      <th>Duty cycle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @remotes.each do |remote| %>
      <tr>
        <td><%= remote.name %></td>
        <td><%= remote.brand.name %></td>
        <td><%= remote.model %></td>
        <td><%= remote.supported_devices %></td>
        <td><%= remote.bits %></td>
        <td><%= remote.flags %></td>
        <td><%= remote.include %></td>
        <td><%= remote.manual_sort %></td>
        <td><%= remote.suppress_repeat %></td>
        <td><%= remote.driver %></td>
        <td><%= remote.eps %></td>
        <td><%= remote.aeps %></td>
        <td><%= remote.header %></td>
        <td><%= remote.zero %></td>
        <td><%= remote.one %></td>
        <td><%= remote.two %></td>
        <td><%= remote.three %></td>
        <td><%= remote.ptrail %></td>
        <td><%= remote.plead %></td>
        <td><%= remote.foot %></td>
        <td><%= remote.repeat %></td>
        <td><%= remote.pre_data_bits %></td>
        <td><%= remote.pre_data %></td>
        <td><%= remote.post_data_bits %></td>
        <td><%= remote.post_data %></td>
        <td><%= remote.pre %></td>
        <td><%= remote.post %></td>
        <td><%= remote.gap %></td>
        <td><%= remote.repeat_gap %></td>
        <td><%= remote.min_repeat %></td>
        <td><%= remote.toggle_bit %></td>
        <td><%= remote.toggle_bit_mask %></td>
        <td><%= remote.repeat_mask %></td>
        <td><%= remote.frequency %></td>
        <td><%= remote.duty_cycle %></td>
        <td><%= link_to 'Show', remote %></td>
        <td><%= link_to 'Edit', edit_remote_path(remote) %></td>
        <td><%= link_to 'Destroy', remote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Remote', new_remote_path %>

app/views/remotes/new.html.erb
<h1>New Remote</h1>

<%= render 'form', remote: @remote %>

<%= link_to 'Back', remotes_path %>

app/views/remotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @remote.name %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @remote.brand.name %>
</p>

<p>
  <strong>Model:</strong>
  <%= @remote.model %>
</p>

<p>
  <strong>Supported devices:</strong>
  <%= @remote.supported_devices %>
</p>

<p>
  <strong>Bits:</strong>
  <%= @remote.bits %>
</p>

<p>
  <strong>Flags:</strong>
  <%= @remote.flags %>
</p>

<p>
  <strong>Include:</strong>
  <%= @remote.include %>
</p>

<p>
  <strong>Manual sort:</strong>
  <%= @remote.manual_sort %>
</p>

<p>
  <strong>Suppress repeat:</strong>
  <%= @remote.suppress_repeat %>
</p>

<p>
  <strong>Driver:</strong>
  <%= @remote.driver %>
</p>

<p>
  <strong>Eps:</strong>
  <%= @remote.eps %>
</p>

<p>
  <strong>Aeps:</strong>
  <%= @remote.aeps %>
</p>

<p>
  <strong>Header:</strong>
  <%= @remote.header %>
</p>

<p>
  <strong>Zero:</strong>
  <%= @remote.zero %>
</p>

<p>
  <strong>One:</strong>
  <%= @remote.one %>
</p>

<p>
  <strong>Two:</strong>
  <%= @remote.two %>
</p>

<p>
  <strong>Three:</strong>
  <%= @remote.three %>
</p>

<p>
  <strong>Ptrail:</strong>
  <%= @remote.ptrail %>
</p>

<p>
  <strong>Plead:</strong>
  <%= @remote.plead %>
</p>

<p>
  <strong>Foot:</strong>
  <%= @remote.foot %>
</p>

<p>
  <strong>Repeat:</strong>
  <%= @remote.repeat %>
</p>

<p>
  <strong>Pre data bits:</strong>
  <%= @remote.pre_data_bits %>
</p>

<p>
  <strong>Pre data:</strong>
  <%= @remote.pre_data %>
</p>

<p>
  <strong>Post data bits:</strong>
  <%= @remote.post_data_bits %>
</p>

<p>
  <strong>Post data:</strong>
  <%= @remote.post_data %>
</p>

<p>
  <strong>Pre:</strong>
  <%= @remote.pre %>
</p>

<p>
  <strong>Post:</strong>
  <%= @remote.post %>
</p>

<p>
  <strong>Gap:</strong>
  <%= @remote.gap %>
</p>

<p>
  <strong>Repeat gap:</strong>
  <%= @remote.repeat_gap %>
</p>

<p>
  <strong>Min repeat:</strong>
  <%= @remote.min_repeat %>
</p>

<p>
  <strong>Toggle bit:</strong>
  <%= @remote.toggle_bit %>
</p>

<p>
  <strong>Toggle bit mask:</strong>
  <%= @remote.toggle_bit_mask %>
</p>

<p>
  <strong>Repeat mask:</strong>
  <%= @remote.repeat_mask %>
</p>

<p>
  <strong>Frequency:</strong>
  <%= @remote.frequency %>
</p>

<p>
  <strong>Duty cycle:</strong>
  <%= @remote.duty_cycle %>
</p>

<%= link_to 'Edit', edit_remote_path(@remote) %> |
<%= link_to 'Back', remotes_path %>