config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Site root
  root 'static_pages#home'

  # User routes
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :keys
  resources :remotes
  resources :devices
  resources :device_types
  resources :device_models
  resources :device_brands
  resources :locations
end

app/controllers/device_types_controller.rb
class DeviceTypesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_device_type, only: [:show, :edit, :update, :destroy]

  # GET /device_types
  # GET /device_types.json
  def index
    @device_types = DeviceType.all
  end

  # GET /device_types/1
  # GET /device_types/1.json
  def show
  end

  # GET /device_types/new
  def new
    @device_type = DeviceType.new
  end

  # GET /device_types/1/edit
  def edit
  end

  # POST /device_types
  # POST /device_types.json
  def create
    @device_type = current_user.submitted_device_types.new(device_type_params)

    respond_to do |format|
      if @device_type.save
        format.html { redirect_to @device_type, notice: 'Device type was successfully created.' }
        format.json { render :show, status: :created, location: @device_type }
      else
        format.html { render :new }
        format.json { render json: @device_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /device_types/1
  # PATCH/PUT /device_types/1.json
  def update
    respond_to do |format|
      if @device_type.update(device_type_params)
        format.html { redirect_to @device_type, notice: 'Device type was successfully updated.' }
        format.json { render :show, status: :ok, location: @device_type }
      else
        format.html { render :edit }
        format.json { render json: @device_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /device_types/1
  # DELETE /device_types/1.json
  def destroy
    @device_type.destroy
    respond_to do |format|
      format.html { redirect_to device_types_url, notice: 'Device type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device_type
      @device_type = DeviceType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_type_params
      params.require(:device_type).permit(:name)
    end
end

app/helpers/device_types_helper.rb
module DeviceTypesHelper
end

app/views/device_types/_form.html.erb
<%= form_with(model: device_type, local: true) do |f| %>
  <% if device_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device_type.errors.count, "error") %> prohibited this device_type from being saved:</h2>

      <ul>
      <% device_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, id: :device_type_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/device_types/edit.html.erb
<h1>Editing Device Type</h1>

<%= render 'form', device_type: @device_type %>

<%= link_to 'Show', @device_type %> |
<%= link_to 'Back', device_types_path %>

app/views/device_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Device Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Submitter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @device_types.each do |device_type| %>
      <tr>
        <td><%= device_type.name %></td>
        <td><%= device_type.submitter.name %></td>
        <td><%= link_to 'Show', device_type %></td>
        <td><%= link_to 'Edit', edit_device_type_path(device_type) %></td>
        <td><%= link_to 'Destroy', device_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device Type', new_device_type_path %>

app/views/device_types/new.html.erb
<h1>New Device Type</h1>

<%= render 'form', device_type: @device_type %>

<%= link_to 'Back', device_types_path %>

app/views/device_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @device_type.name %>
</p>

<p>
  <strong>Submitter:</strong>
  <%= @device_type.submitter.name %>
</p>

<%= link_to 'Edit', edit_device_type_path(@device_type) %> |
<%= link_to 'Back', device_types_path %>