config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Site root
  root 'static_pages#home'

  # User routes
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :keys
  resources :remotes
  resources :devices
  resources :device_types
  resources :device_models
  resources :device_brands
  resources :locations
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-dark fixed-top navbar-toggleable-sm">
  <%= link_to 'Bernard.ai', root_path, class: 'navbar-brand', id: 'logo' %>

  <ul class="nav">
  <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to 'Brands', device_brands_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Models', device_models_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Types', device_types_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Devices', devices_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Remotes', remotes_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Keys', keys_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Locations', locations_path, class: 'nav-link' %>
    </li>
    <li class="nav-item dropdown">
      <%= link_to '', class: 'nav-link dropdown-toggle',
                      id: 'user_menu_toggler',
                      data: { toggle: 'dropdown' },
                      aria: { expanded: 'false', haspopup: 'true' } do %>
        <%= fa_icon 'user-o' %>
      <% end %>
      <div class="dropdown-menu dropdown-menu-right" id="user_menu" aria-labelledby="user_menu_toggler">
        <%= link_to 'Edit account', edit_user_registration_path(current_user), class: 'dropdown-item' %>
        <div class="dropdown-divider"></div>
        <%= link_to 'Sign out...', destroy_user_session_path, method: 'delete', class: 'dropdown-item' %>
      </div>
    </li>
  <% else %>
      <li class="nav-item active">
        <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
      </li>
  <% end %>
  </ul>
</nav>

app/views/layouts/_rails_default_header.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>
      <%= if content_for?(:title) then yield(:title) + ' | ' end %>
      Bernard.ai
    </title>
    <%= render 'layouts/rails_default_header' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <% #Include debug console on development environment %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>